base_frame: world
tool_frame: flange

flange:
  # molle di "repulsione"
  spring: [5,5,5]
  damper: [5,5,5]
  activation_distance: 1 #metri
  # molle di "attrazione"
  self_spring: [5,5,5]
  self_damper: [5,5,5]

link3:
  spring: [0.10,0.10,0.10]
  damper: [5,5,5]
  activation_distance: 1
  self_spring: [10,10,10]
  self_damper: [5,5,5]

joint_spring: [1,1,1,1,1,1]
joint_damper: [0.1,0.1,0.1,0.1,0.1,0.1]
