base_frame: world
tool_frame: open_tip

shoulder_link:
  # molle di "repulsione"
  # spring: [0.10,0.10,0.10]
  # spring: [1.0,1.0,1.0]
  spring: [10,10,10]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [1100,1100,1100]
  self_damper: [0.5,0.5,0.5]

upper_arm_link:
  # molle di "repulsione"
  # spring: [0.10,0.10,0.10]
  # spring: [1.0,1.0,1.0]
  spring: [10,10,10]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [1070,1070,1070]
  self_damper: [0.5,0.5,0.5]

forearm_link:
  # molle di "repulsione"
  # spring: [0.11,0.11,0.11]
  # spring: [1.1,1.1,1.1]
  spring: [11,11,11]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [1050,1050,1050]
  self_damper: [0.5,0.5,0.5]

wrist_1_link:
  # molle di "repulsione"
  # spring: [0.13,0.13,0.13]
  # spring: [1.3,1.3,1.3]
  spring: [13,13,13]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [1020,1020,1020]
  self_damper: [0.5,0.5,0.5]

wrist_2_link:
  # molle di "repulsione"
  # spring: [0.14,0.14,0.14]
  # spring: [1.4,1.4,1.4]
  spring: [14,14,14]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [1000,1000,1000]
  self_damper: [0.5,0.5,0.5]

wrist_3_link:
  # molle di "repulsione"
  # spring: [0.15,0.15,0.15]
  # spring: [1.5,1.5,1.5]
  spring: [15,15,15]
  damper: [0.001,0.001,0.001]
  activation_distance: 1.0 #metri
  #molle di "attrazione"
  self_spring: [980,980,980]
  self_damper: [0.5,0.5,0.5]

joint_spring: [60,30,30,12,12,12]
joint_damper: [70,70,70,30,30,30]

max_joint_deflaction: [0.1,0.12,0.15,0.2,0.25,0.3] # [0.15,0.15,0.25,0.2,0.25,0.3] [0.1,0.12,0.15,0.2,0.25,0.3] [10.0,10.0,10.0,10.0,10.0,10.0]

max_reduction: 0.5
upper_limit_repulsion: 0.9 #0.9
lower_limit_repulsion: 0.1 #0.1
