base_frame: world
tool_frame: open_tip

tool0:
  # molle di "repulsione"
  spring: [5,5,5]
  damper: [0.001,0.001,0.001]
  activation_distance: 0.5 #metri
  #molle di "attrazione"
  self_spring: [0,0,0]
  self_damper: [0,0,0]

#forearm_link:
  #spring: [0.10,0.10,0.10]
  #damper: [5,5,5]
  #activation_distance: 1
  #self_spring: [10,10,10]
  #self_damper: [5,5,5]

joint_spring: [1.2,1.2,1.2,0.12,0.12,0.12]
joint_damper: [1.6,1.6,1.6,0.4,0.4,0.4]
