base_frame: world
tool_frame: open_tip

tool0:
  # molle di "repulsione"
  # spring: [0.01,0.01,0.01]
  # spring: [0.1,0.1,0.1]
  spring: [1,1,1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [11,11,11]
  # self_spring: [110,110,110]
  self_spring: [1100,1100,1100]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

shoulder_link:
  # molle di "repulsione"
  # spring: [0.01,0.01,0.01]
  # spring: [0.1,0.1,0.1]
  spring: [1,1,1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [11,11,11]
  # self_spring: [110,110,110]
  self_spring: [1100,1100,1100]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

upper_arm_link:
  # molle di "repulsione"
  # spring: [0.01,0.01,0.01]
  # spring: [0.1,0.1,0.1]
  spring: [1,1,1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [10.75,10.75,10.75]
  # self_spring: [107,107,107]
  self_spring: [1070,1070,1070]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

forearm_link:
  # molle di "repulsione"
  # spring: [0.011,0.011,0.011]
  # spring: [0.11,0.11,0.11]
  spring: [1.1,1.1,1.1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [10.5,10.5,10.5]
  # self_spring: [105,105,105]
  self_spring: [1050,1050,1050]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

wrist_1_link:
  # molle di "repulsione"
  # spring: [0.013,0.013,0.013]
  # spring: [0.13,0.13,0.13]
  spring: [1.3,1.3,1.3]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [10.25,10.25,10.25]
  # self_spring: [102,102,102]
  self_spring: [1020,1020,1020]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

wrist_2_link:
  # molle di "repulsione"
  # spring: [0.014,0.014,0.014]
  # spring: [0.14,0.14,0.14]
  spring: [1.4,1.4,1.4]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [10,10,10]
  # self_spring: [100,100,100]
  self_spring: [1000,1000,1000]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

wrist_3_link:
  # molle di "repulsione"
  # spring: [0.015,0.015,0.015]
  # spring: [0.15,0.15,0.15]
  spring: [1.5,1.5,1.5]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: # [0.11,0.11,0.11]
  # self_spring: [9.75,9.75,9.75]
  # self_spring: [98,98,98]
  self_spring: [980,980,980]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

ee_link:
  # molle di "repulsione"
  # spring: [0.016,0.016,0.016]
  # spring: [0.8,0.8,0.8]
  spring: [8,8,8]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  # self_spring: [0.11,0.11,0.11]
  # self_spring: [9.5,9.5,9.5]
  # self_spring: [95,95,95]
  self_spring: [950,950,950]
  # self_damper: [5,5,5]
  self_damper: [0.5,0.5,0.5]
  # self_damper: [0.01,0.01,0.01]

# joint_spring: [1.2,1.2,1.2,0.12,0.12,0.12]
joint_spring: [60,60,60,12,12,12]
# joint_spring: [120,120,120,12,12,12]
joint_damper: [70,70,7,3,3,3]
# joint_damper: [3,3,3,0.8,0.4,0.3]
# joint_damper: [1.4,1.4,1.4,0.3,0.3,0.3]

max_joint_deflaction: [0.1,0.1,0.12,0.2,0.25,0.3] # [0.1,0.12,0.15,0.2,0.25,0.3] [1,1,1,1,1,1]

max_reduction: 0.5
upper_limit_repulsion: 1.0 #0.9
lower_limit_repulsion: 0.0 #0.1
