base_frame: world
tool_frame: open_tip

tool0:
  # molle di "repulsione"
  spring: [0.1,0.1,0.1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [11,11,11]
  self_damper: [0.001,0.001,0.001]

shoulder_link:
  # molle di "repulsione"
  spring: [0.1,0.1,o.1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [11,11,11]
  self_damper: [0.001,0.001,0.001]

upper_arm_link:
  # molle di "repulsione"
  spring: [0.1,0.1,0.1]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [10.75,10.75,10.75]
  self_damper: [0.001,0.001,0.001]

forearm_link:
  # molle di "repulsione"
  spring: [0.11,0.11,0.11]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [10.5,10.5,10.5]
  self_damper: [0.001,0.001,0.001]

wrist_1_link:
  # molle di "repulsione"
  spring: [0.13,0.13,0.13]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [10.25,10.25,10.25]
  self_damper: [0.001,0.001,0.001]

wrist_2_link:
  # molle di "repulsione"
  spring: [0.14,0.14,0.14]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [10,10,10]
  self_damper: [0.001,0.001,0.001]

wrist_3_link:
  # molle di "repulsione"
  spring: [0.15,0.15,0.15]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [9.75,9.75,9.75]
  self_damper: [0.001,0.001,0.001]

ee_link:
  # molle di "repulsione"
  # spring: [0.16,0.16,0.16]
  spring: [0.8,0.8,0.8]
  damper: [0.001,0.001,0.001]
  activation_distance: 1 #metri
  #molle di "attrazione"
  self_spring: [9.5,9.5,9.5]
  self_damper: [0.001,0.001,0.001]

joint_spring: [1.2,1.2,1.2,0.12,0.12,0.12]
joint_damper: [1.4,1.4,1.4,0.3,0.3,0.3]

max_joint_deflaction: [0.1,0.12,0.15,0.2,0.25,0.3] #[1,1,1,1,1,1]

max_reduction: 0.5
upper_limit_repulsion: 1.0 #0.9
lower_limit_repulsion: 0.0 #0.1
